[package]
name = "http_trace"
version = "0.1.0"
authors = ["Billy Richardson <richardsondev>"]
edition = "2018"

[dependencies]
openssl = { version = "0.10", features = ["vendored"] }
reqwest = { version = "0.13", features = ["json"] }
tokio = { version = "1", features = ["full"] }
url = "2"
